
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { UserProvider } from "./context/context";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <UserProvider>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </UserProvider>

      </body>
    </html>
  );
}
